//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Cust2 = new HashSet<Cust2>();
        }
    
        public int Address_ID { get; set; }
        public string Address_Numder_Appartment { get; set; }
        public string Address_Number_Street { get; set; }
        public string Address_Name_Street { get; set; }
        public string Address_City { get; set; }
        public string Address_ZIPCODE { get; set; }
        public string Address_State { get; set; }
        public string Address_Country { get; set; }
        public string Address_line1 { get; set; }
        public string Address_line2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cust2> Cust2 { get; set; }
    }
}
