//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bouquet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bouquet()
        {
            this.Flo_Order = new HashSet<Flo_Order>();
            this.Order_Del = new HashSet<Order_Del>();
        }
    
        public int Bouquet_ID { get; set; }
        public string Bouquet_Name { get; set; }
        public Nullable<decimal> Bouquet_Price_S { get; set; }
        public Nullable<decimal> Bouquet_Price_M { get; set; }
        public Nullable<decimal> Bouquet_Price_L { get; set; }
        public string Bouquet_Size { get; set; }
        public byte[] Bouquet_Pictures { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flo_Order> Flo_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Del> Order_Del { get; set; }
    }
}
