//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Flo_Order = new HashSet<Flo_Order>();
            this.Payment_Methods = new HashSet<Payment_Methods>();
        }
    
        public int Cust_ID { get; set; }
        public string Cust_Fname { get; set; }
        public string Cust_Lname { get; set; }
        public string Cust_Midname { get; set; }
        public string Cust_Email { get; set; }
        public string Cust_Login { get; set; }
        public string Cust_Sex { get; set; }
        public string Cust_Password { get; set; }
        public decimal Cust_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flo_Order> Flo_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Methods> Payment_Methods { get; set; }
    }
}
