//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flo_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flo_Order()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Statistics = new HashSet<Statistic>();
        }
    
        public int Order_ID { get; set; }
        public int Bouquet_ID { get; set; }
        public int Florist_ID { get; set; }
        public int Cust_ID { get; set; }
        public int Driver_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<decimal> Bouquet_Quontity { get; set; }
        public Nullable<System.DateTime> Date_a206yuriyed { get; set; }
        public string Order_Status { get; set; }
    
        public virtual Bouquet Bouquet { get; set; }
        public virtual Cust2 Cust2 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Florist Florist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistic> Statistics { get; set; }
    }
}
