//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_ID { get; set; }
        public int Order_ID { get; set; }
        public Nullable<decimal> Invoice_Total { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
    
        public virtual Flo_Order Flo_Order { get; set; }
    }
}
