//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Pass { get; set; }
        public Nullable<bool> User_Status { get; set; }
        public Nullable<int> User_of_Group { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
