//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowers_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int Warehouse_ID { get; set; }
        public int Florist_ID { get; set; }
        public string Warehouse_Name { get; set; }
        public string Warehouse_City { get; set; }
        public string Warehouse_Address { get; set; }
        public Nullable<decimal> Warehouse_Phone { get; set; }
        public string Warehouse_Email { get; set; }
    
        public virtual Florist Florist { get; set; }
    }
}
